### ISSUE TITLE
Achieve decision: What would be an ideal length for a K8s promotion?

### ISSUE THREAD

**Issue by lasomethingsomething** [kubernetes-sigs/k8s-container-image-promoter#1126]
This is a problem for the official k8s releases. Not the subprojects of the K8S project.

## Objective 
- SIG reaches a decision based on data that shows what's realistic.
- In the future, SIG uses this decision to plan work to implement the target.

## Tasks to achieve the objective
By 1-3 contributors:
- [ ] Do research on the topic
- [ ] Collect questions from SIG members as part of your research phase
- [ ] Prepare a brief (1-2 pages max) proposal evaluating pros, cons, and tradeoffs
- [ ] Share proposal with SIG (mailing list, Slack thread, at community meeting)
By the SIG/group:
- [ ] SIG members provide input on findings/raise questions
- [ ] After a timeboxed review period (to be determined), SIG members regroup to make a decision
- [ ] Log decision for community awareness
- [ ] Plan next steps

![Image](https://github.com/kubernetes-sigs/promo-tools/assets/2453640/f4c08f06-224b-4c83-8546-c2a2d46159ec)

![Image](https://github.com/kubernetes-sigs/promo-tools/assets/2453640/e5402ccf-2f00-4772-8fef-9baeedfc2c82)

**Comment by lasomethingsomething** [comment]
@saschagrunert @xmudrii Heya both, you did #1124 partly to inform this issue. Do you think the results here https://github.com/kubernetes-sigs/promo-tools/issues/1124#issuecomment-1849583718 would be different now, after time has passed? 

If not, do you have thoughts on what a good benchmark for this issue might be?

**Comment by saschagrunert** [comment]
We haven't improved much on the overall timings so I'd assume the results are still valid.

**Comment by xmudrii** [comment]
Generally, building packages is now much more reliable and nomock stage doesn't take 4h, but image promotion is still taking a long time. We're looking into how we can improve this and we'll hopefully come with a plan soon.

**Comment by saschagrunert** [comment]
Closing in favor of https://github.com/kubernetes-sigs/promo-tools/issues/1701, thank you for all the work which went into this. It's consolidated into the single issue.
