### ISSUE TITLE
User research: Find out who are the users and downstream consumers of K8s releases

### ISSUE THREAD

**Issue by lasomethingsomething** [kubernetes-sigs/k8s-container-image-promoter#1133]
## Objective 
- Collect user data to validate assumptions and inform decision-making
- Find out who is using our tools

## Related user stories
- As a downstream consumer of K8s releases, I would like to be able to check the integrity of binaries, container images, documents, and other files that form a K8s release, so that I can trust that the release is secure.
- As a downstream consumer of K8s releases, I would like my releases to comply with SLSA 3, so that I can be maximally confident that my release hasn’t been tampered with. (See also [KEP #3027](https://github.com/kubernetes/enhancements/issues/3027))
- Hyperscalers, products on top of K8s. The notion of trust doesn't apply to them? They don't need K8s to be SLSA 3-compliant. They pull the source code to build something themselves. People trusting us build custom installers (KubeSpray, for example), end users building K8s envs because they don't have a choice, sovereign cloud. 
- How people use the images
- What they expect to have in the images

## Tasks

- [ ] Ask CNCF users tag for ideas on data collection/surveys
- [ ] Seek data on who is using our tools
- [ ] Develop mechanism to collect regular feedback
- [ ] Ask Cluster Lifecycle for their data
- [ ] Involve SIG Contribex Comms/K8s mailing list
- [ ] Maybe Brandon Mitchell should be involved. He led the OCI initiatives including standard, security, artifacts https://github.com/sudo-bmitch

![Image](https://github.com/kubernetes-sigs/promo-tools/assets/2453640/f4c08f06-224b-4c83-8546-c2a2d46159ec)

![Image](https://github.com/kubernetes-sigs/promo-tools/assets/2453640/e5402ccf-2f00-4772-8fef-9baeedfc2c82)

**Comment by LappleApple** [comment]
Notes from survey session:
- keeping detailed questions about packages out of survey for now as they're out of scope (per group)
- need @puerco to weigh in on this question (attached image) to ensure that we're offering the best and most meaningful list of options

![Image](https://github.com/kubernetes-sigs/promo-tools/assets/2453640/c3b17a00-6761-45b8-a613-6b219d388291)

**Comment by xmudrii** [comment]
The survey has been conducted and @LappleApple did the initial data processing, but we still need to draw the conclusion
/remove-lifecycle stale

**Comment by xmudrii** [comment]
I'm not working on this at the moment.
/unassign

**Comment by saschagrunert** [comment]
Closing in favor of https://github.com/kubernetes-sigs/promo-tools/issues/1701, thank you for all the work which went into this. It's consolidated into the single issue.
