### ISSUE TITLE
[Umbrella] Repo improvements

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/k8s-container-image-promoter#266]
This a braindump of tasks I've done / plan on doing to improve the repo...

- [x] Code organization
  - [x] (https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/261) Init submodules, so libraries are importable
  - [x] (https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/260) Init v2 module (needs bazel cleanup first)
  - [x] (https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/262) Migrate `lib/` into `pkg/`
  - [x] (https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/263) Migrate vulnerability dashboard library into `pkg/`
- [x] OWNERS
  - [x] (https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/265) Establish Release Engineering ownership of repo
  - [x] (https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/265) Add active maintainers / prune inactive
  - [x] (https://github.com/kubernetes/k8s.io/pull/1341) Enable OWNERS to perform image promotion
  - [x] (https://github.com/kubernetes/org/pull/2272) Update SIG Release teams to include current CIP maintainers
- [x] Test Infra
  - [x] Contributing
    - [x] RelEng ownership of CI jobs
      - [x] OWNERS update in https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-release/cip/OWNERS: https://github.com/kubernetes/test-infra/pull/23598
      - [x] (https://github.com/kubernetes/test-infra/pull/19599) Inform Release Managers of CI failures
    - [x] (https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/267) Add issue/PR templates
    - [x] (https://github.com/kubernetes/test-infra/pull/19596) Add RelEng labels to repo
    - [x] (https://github.com/kubernetes/test-infra/pull/19597) Enable common prow plugins
    - [x] (https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/268, https://github.com/kubernetes/test-infra/pull/19599) Verify scripts
  - [x] Migrating jobs to K8s Infra - https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/269
- [x] (https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/291, https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/270) Update to klog v2
- [x] CLI tool migration
  - [x] (https://github.com/kubernetes/release/pull/1652, https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/273) Migrate promobot (`promobot-files`, `promobot-generate-manifest`) tools to k/release
  - [x] (https://github.com/kubernetes/release/pull/1652, https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/273) Migrate `cip-mm` to k/release
  - [x] Create Dockerfiles for promobot tools: https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/408
- [x] Remove bazel: https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/300

/sig release
/area release-eng
/wg k8s-infra

cc: @kubernetes-sigs/release-engineering

**Comment by cpanato** [comment]
I will work on the `Test Infra / Contributing` items

**Comment by spiffxp** [comment]
Suggestion for test-infra changes: container-image-promoter jobs that currently run in the google.com-owned prow.k8s.io service cluster should run in community-owned infrastructure instead

Migrating to k8s-infra-prow-build-trusted would involve:
- ensuring there service accounts and workload identity bindings for k8s-infra-prow-build-trusted
  - so the relevant service accounts in here: https://github.com/kubernetes/test-infra/blob/master/config/prow/cluster/trusted_serviceaccounts.yaml
  - should exist or have equivalents here: https://github.com/kubernetes/k8s.io/blob/master/infra/gcp/clusters/projects/k8s-infra-prow-build-trusted/prow-build-trusted/resources/build-serviceaccounts.yaml
  - and bindings should be setup accordingly (I modified https://github.com/kubernetes/k8s.io/blob/master/infra/gcp/ensure-prod-storage.sh a while back, search other scripts to see if there's anything we've missed)
- moving jobs from the test-infra-trusted file to wg-k8s-infra-trusted
  - so from here https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml
  - to here https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/wg-k8s-infra/trusted/wg-k8s-infra-trusted.yaml

**Comment by justaugustus** [comment]
> Suggestion for test-infra changes: container-image-promoter jobs that currently run in the google.com-owned prow.k8s.io service cluster should run in community-owned infrastructure instead

Thanks for all of the details, @spiffxp!
I've opened https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/269 to track this, since it's a bit meaty compared to the other tasks in this umbrella.

**Comment by justaugustus** [comment]
To keep this from being open indefinitely...

Recently merged:
- Image building for `kpromo`: https://github.com/kubernetes-sigs/k8s-container-image-promoter/pull/408

Moved to a separate issue:
- Integrate file promotion into k/k release process: https://github.com/kubernetes/release/issues/2248

Closed with:
- OWNERS update in https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-release/cip/OWNERS: https://github.com/kubernetes/test-infra/pull/23598

/close
