### ISSUE TITLE
Removing Bazel from e2e tests

### ISSUE THREAD

**Issue by tylerferrara** [kubernetes-sigs/k8s-container-image-promoter#304]
Sub-Issue of #300 

Outlining the steps of implementing [Tarball Image Loading](https://docs.google.com/document/d/1tQTb8dqKQtsL1a5jmCDbRg2MEDMkAnT07vrrxyZxLfk/edit?usp=sharing) within CIP.
This involves accomplishing the following:
- [x]  Generate tarball archives for golden-tests #305 #307
- [x]  Add archive loading to test-e2e-cip #306  
- [x]  Replace all Bazel invocations in e2e.go with `go run` #308 
- [x]  Add archive loading to test-e2e-cip-auditor #315 #318 
- [x]  Replace all Bazel invocations in cip-auditor-e2e.go with `go run` #316 
- [x]  Cleanup tests, golden image data, and archives #320 #319 #317 

/sig release
/area release-eng

/assign @tylerferrara 
cc: @listx @amwat @justaugustus @kubernetes-sigs/release-engineering

**Comment by tylerferrara** [comment]
Completed, closing.
